### ISSUE TITLE
1.8 crash

### ISSUE THREAD

**Issue by sigurd4** [Dynious/VersionChecker#76]
in forge 1.8-11.14.3.1450.

i'm guessing my forge version is too new for the mod, as the field is named something else in my version of forge than in yours.

log:

```
[02:22:14] [main/INFO] [GradleStart]: accessToken: modstest
[02:22:14] [main/INFO] [GradleStart]: version: 1.7
[02:22:14] [main/INFO] [GradleStart]: username: sigurd-s@online.no
[02:22:14] [main/INFO] [GradleStart]: Extra: [-Dfml.ignoreInvalidMinecraftCertificates=true]
[02:22:14] [main/INFO] [GradleStart]: Password found, attempting login
[02:22:14] [main/INFO]: Logging in with username & password
[02:22:15] [main/INFO] [GradleStart]: Login Succesful!
[02:22:15] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, [{"name":"twitch_access_token","value":"2utgone6a1douse86zz8m3ac39et5ch"}], --assetsDir, C:/Users/Sigurd/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --userType, mojang, --accessToken, {REDACTED}, --version, 1.7, --uuid, 31ee010964264ea0987165936649f6d2, --username, sigurd4, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, -Dfml.ignoreInvalidMinecraftCertificates=true, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[02:22:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[02:22:15] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[02:22:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[02:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[02:22:15] [main/INFO] [FML]: Forge Mod Loader version 8.99.124.1450 for Minecraft 1.8 loading
[02:22:15] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_25
[02:22:15] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[02:22:15] [main/WARN] [FML]: The coremod com.dynious.versionchecker.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[02:22:15] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[02:22:15] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[02:22:15] [main/INFO] [GradleStart]: Injecting location in coremod TMIForgeLoader
[02:22:15] [main/INFO] [GradleStart]: Injecting location in coremod com.dynious.versionchecker.asm.LoadingPlugin
[02:22:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:22:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[02:22:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[02:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[02:22:15] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[02:22:19] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[02:22:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[02:22:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[02:22:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[02:22:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[02:22:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[02:22:19] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[02:22:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[02:22:19] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[02:22:20] [main/INFO] [STDOUT]: [net.minecraft.client.main.Main:main:59]: Completely ignored arguments: [-Dfml.ignoreInvalidMinecraftCertificates, true]
[02:22:20] [Client thread/INFO]: Setting user: sigurd4
[02:22:23] [Client thread/INFO]: LWJGL Version: 2.9.1
[02:22:24] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:235]: ---- Minecraft Crash Report ----
WARNING: coremods are present:
LoadingPlugin (VersionChecker-1.2.2.jar)
TMIForgeLoader (TooManyItems2015_02_14_1.8_Forge.jar)
Contact their authors BEFORE contacting forge
// Sorry :(
Time: 06.08.15 02:22
Description: Loading screen debug info
This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 956618704 bytes (912 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: 
Loaded coremods (and transformers): 
LoadingPlugin (VersionChecker-1.2.2.jar)

TMIForgeLoader (TooManyItems2015_02_14_1.8_Forge.jar)
TMIForgeTransformer
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.62' Renderer: 'GeForce GT 530/PCIe/SSE2'
[02:22:24] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[02:22:24] [Client thread/INFO] [FML]: MinecraftForge v11.14.3.1450 Initialized
[02:22:24] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[02:22:24] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[02:22:24] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[02:22:24] [Client thread/INFO] [FML]: Searching C:\Users\Sigurd\Documents\Minecraft\bioshock mod workspace\SpectralGuns\eclipse\client\mods for mods
[02:22:26] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[02:22:27] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, TooManyItems, spectralguns, VersionChecker] at CLIENT
[02:22:27] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, TooManyItems, spectralguns, VersionChecker] at SERVER
[02:22:27] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:SpectralGuns, FMLFileResourcePack:Version Checker
[02:22:27] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[02:22:27] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[02:22:27] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[02:22:27] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[02:22:27] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[02:22:28] [Client thread/INFO] [FML]: Applying holder lookups
[02:22:28] [Client thread/INFO] [FML]: Holder lookups applied
[02:22:28] [Client thread/INFO] [FML]: Injecting itemstacks
[02:22:28] [Client thread/INFO] [FML]: Itemstack injection complete
[02:22:28] [Sound Library Loader/INFO]: Starting up SoundSystem...
[02:22:28] [Thread-11/INFO]: Initializing LWJGL OpenAL
[02:22:28] [Thread-11/INFO]: (The LWJGL binding of OpenAL. For more information, see http://www.lwjgl.org)
[02:22:28] [Thread-11/INFO]: OpenAL initialized.
[02:22:29] [Sound Library Loader/INFO]: Sound engine started
[02:22:29] [Twitch authenticator/ERROR]: Given twitch access token is invalid
[02:22:33] [Client thread/INFO]: Created: 512x512 textures-atlas
[02:22:34] [Thread-13/INFO] [VersionChecker]: Received version check from mod VersionChecker
[02:22:34] [Client thread/INFO] [FML]: Injecting itemstacks
[02:22:34] [Client thread/INFO] [FML]: Itemstack injection complete
[02:22:35] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 6 mods
[02:22:35] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:SpectralGuns, FMLFileResourcePack:Version Checker
[02:22:35] [Client thread/INFO]: SoundSystem shutting down...
[02:22:35] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[02:22:35] [Sound Library Loader/INFO]: Starting up SoundSystem...
[02:22:35] [Thread-14/INFO]: Initializing LWJGL OpenAL
[02:22:35] [Thread-14/INFO]: (The LWJGL binding of OpenAL. For more information, see http://www.lwjgl.org)
[02:22:35] [Thread-14/INFO]: OpenAL initialized.
[02:22:35] [Thread-13/INFO] [VersionChecker]: Version Checker Status for Version Checker: CURRENT
[02:22:35] [Sound Library Loader/INFO]: Sound engine started
[02:22:38] [Client thread/INFO]: Created: 512x512 textures-atlas
[02:22:39] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$InitGuiEvent$Pre@441c8fa3:
java.lang.NoSuchFieldError: field_146294_l
at com.dynious.versionchecker.client.gui.GuiMainMenuHandler.initGui(GuiMainMenuHandler.java:25) ~[GuiMainMenuHandler.class:?]
at com.dynious.versionchecker.event.EventHandler.onGuiInit(EventHandler.java:24) ~[EventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EventHandler_onGuiInit_InitGuiEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:549) [GuiScreen.class:?]
at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:983) [Minecraft.class:?]
at net.minecraft.client.Minecraft.startGame(Minecraft.java:538) [Minecraft.class:?]
at net.minecraft.client.Minecraft.run(Minecraft.java:356) [Minecraft.class:?]
at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
at GradleStart.main(Unknown Source) [start/:?]
[02:22:39] [Client thread/ERROR] [FML]: Index: 1 Listeners:
[02:22:39] [Client thread/ERROR] [FML]: 0: NORMAL
[02:22:39] [Client thread/ERROR] [FML]: 1: ASM: com.dynious.versionchecker.event.EventHandler@f58011d onGuiInit(Lnet/minecraftforge/client/event/GuiScreenEvent$InitGuiEvent;)V
[02:22:39] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:663]: ---- Minecraft Crash Report ----
WARNING: coremods are present:
LoadingPlugin (VersionChecker-1.2.2.jar)
TMIForgeLoader (TooManyItems2015_02_14_1.8_Forge.jar)
Contact their authors BEFORE contacting forge
// Sorry :(
Time: 06.08.15 02:22
Description: Initializing game
java.lang.NoSuchFieldError: field_146294_l
at com.dynious.versionchecker.client.gui.GuiMainMenuHandler.initGui(GuiMainMenuHandler.java:25)
at com.dynious.versionchecker.event.EventHandler.onGuiInit(EventHandler.java:24)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EventHandler_onGuiInit_InitGuiEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:549)
at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:983)
at net.minecraft.client.Minecraft.startGame(Minecraft.java:538)
at net.minecraft.client.Minecraft.run(Minecraft.java:356)
at net.minecraft.client.main.Main.main(Main.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
at GradleStart.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
at com.dynious.versionchecker.client.gui.GuiMainMenuHandler.initGui(GuiMainMenuHandler.java:25)
at com.dynious.versionchecker.event.EventHandler.onGuiInit(EventHandler.java:24)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EventHandler_onGuiInit_InitGuiEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:549)
at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:983)
at net.minecraft.client.Minecraft.startGame(Minecraft.java:538)
-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.run(Minecraft.java:356)
at net.minecraft.client.main.Main.main(Main.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
at GradleStart.main(Unknown Source)
-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 679646888 bytes (648 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 6 mods loaded, 6 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJA FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.3.1450.jar) 
UCHIJA Forge{11.14.3.1450} [Minecraft Forge] (forgeSrc-1.8-11.14.3.1450.jar) 
UCHIJA TooManyItems{1.8} [TooManyItems] (minecraft.jar) 
UCHIJA spectralguns{1.3} [SpectralGuns] (bin) 
UCHIJA VersionChecker{1.2.2} [Version Checker] (VersionChecker-1.2.2.jar) 
Loaded coremods (and transformers): 
LoadingPlugin (VersionChecker-1.2.2.jar)

TMIForgeLoader (TooManyItems2015_02_14_1.8_Forge.jar)
TMIForgeTransformer
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.62' Renderer: 'GeForce GT 530/PCIe/SSE2'
Launched Version: 1.7
LWJGL: 2.9.1
OpenGL: GeForce GT 530/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.62, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
[02:22:39] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:663]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Sigurd\Documents\Minecraft\bioshock mod workspace\SpectralGuns\eclipse\client\.\crash-reports\crash-2015-08-06_02.22.39-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
```

**Comment by sigurd4** [comment]
tested outside of modding environment, and it seems to work then. though it would be great to be able to test my interaction with your mod inside of the modding environment.

**Comment by squeek502** [comment]
Try updating the mappings in VersionChecker's build.gradle file:

https://github.com/Dynious/VersionChecker/blob/master/build.gradle#L35

and then build VersionChecker for yourself. That might solve the issue.

**Comment by Geforce132** [comment]
Oh, you're running reobfuscated (re-built) mods in a dev. environment? You will need to install CodeChickenCore to deobfuscate the mod when you launch the game. When CCC runs, it'll ask you for a "conf" file, point it to C:/Users/*name*/.gradle/caches/minecraft/net/minecraftforge/forge/*version*/unpacked/conf. That should help.

**Comment by sigurd4** [comment]
thank you so much! that fixes two of my issues at the same time. i had no idea where to point ccc's conf file thing either. :D

**Comment by Geforce132** [comment]
No problem. :)

**Comment by sigurd4** [comment]
cant get it to work, though i figure it's better that i ask chichenbones about this instead.

**Comment by Geforce132** [comment]
What's the error?
